// <auto-generated />
using System;
using ConsoleApp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp.Ride", b =>
                {
                    b.Property<DateTime?>("DropoffDatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("tpep_dropoff_datetime");

                    b.Property<int?>("DropoffLocationId")
                        .HasColumnType("int")
                        .HasColumnName("DOLocationID");

                    b.Property<double?>("FareAmount")
                        .HasColumnType("float")
                        .HasColumnName("fare_amount");

                    b.Property<int?>("PassengersCount")
                        .HasColumnType("int")
                        .HasColumnName("passenger_count");

                    b.Property<DateTime?>("PickupDatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("tpep_pickup_datetime");

                    b.Property<int?>("PickupLocationId")
                        .HasColumnType("int")
                        .HasColumnName("PULocationID");

                    b.Property<int?>("SecondsTravelled")
                        .HasColumnType("int")
                        .HasColumnName("seconds_travelled");

                    b.Property<string>("StoreAndFwdFlag")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("store_and_fwd_flag");

                    b.Property<double?>("TipAmount")
                        .HasColumnType("float")
                        .HasColumnName("tip_amount");

                    b.Property<double?>("TripDistance")
                        .HasColumnType("float")
                        .HasColumnName("trip_distance");

                    b.HasIndex("PickupLocationId");

                    b.HasIndex("SecondsTravelled");

                    b.HasIndex("TripDistance");

                    b.ToTable("Rides");
                });
#pragma warning restore 612, 618
        }
    }
}
